# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNBsBpUXiByc3tRwv8V8IRosi7qCFovC
"""

# Take input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Add the two numbers
sum = num1 + num2

# Display the result
print("The sum of", num1, "and", num2, "is:", sum)